############################################################################
# Contest 2026 team 094 LVGL framebuffer test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = lvgl_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 16384
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_LVGL_TEST)

MAINSRC = lvgl_test_main.c

include $(APPDIR)/Application.mk
