############################################################################
# Contest 2026 team 094 button test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = button_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_BUTTON_TEST)

MAINSRC = button_test_main.c

include $(APPDIR)/Application.mk
