############################################################################
# Contest 2026 team 094 LVGL recorder app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = recorder
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_RECORDER_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_RECORDER_APP)

MAINSRC = recorder_app_main.c

include $(APPDIR)/Application.mk
