############################################################################
# Contest 2026 team 094 speaker test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = speaker_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_SPEAKER_TEST)

MAINSRC = speaker_test_main.c

include $(APPDIR)/Application.mk
