############################################################################
# Contest 2026 team 094 TF-card test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = tf_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 3072
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_TF_TEST)

MAINSRC = tf_test_main.c

include $(APPDIR)/Application.mk
