############################################################################
# Contest 2026 team 094 GT911 probe app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = gt911_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_GT911_TEST)

MAINSRC = gt911_test_main.c

include $(APPDIR)/Application.mk
