############################################################################
# Contest 2026 team 094 framebuffer test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = fb_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_FB_TEST)

MAINSRC = fb_test_main.c

include $(APPDIR)/Application.mk
