############################################################################
# Contest 2026 team 094 buzzer test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = buzzer_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_BUZZER_TEST)

MAINSRC = buzzer_test_main.c

include $(APPDIR)/Application.mk
