############################################################################
# Contest 2026 team 094 direction-key test app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = dpad_test
PRIORITY  = SCHED_PRIORITY_DEFAULT
STACKSIZE = 2048
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_DPAD_TEST)

MAINSRC = dpad_test_main.c

include $(APPDIR)/Application.mk
