############################################################################
# Contest 2026 team 094 SDIO Wi-Fi probe app
############################################################################

include $(APPDIR)/Make.defs

PROGNAME = wifi_test
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = 3072
MODULE = $(CONFIG_LVX_USE_DEMO_CONTEST2026_094_WIFI_TEST)

MAINSRC = wifi_test_main.c

include $(APPDIR)/Application.mk
